version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: flowforge-mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: flowforge
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - flowforge-network

  mongo-express:
    image: mongo-express:latest
    container_name: flowforge-mongo-express
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_URL: mongodb://admin:admin@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
    networks:
      - flowforge-network

  backend:
    build: ./Backend
    container_name: flowforge-backend
    restart: always
    environment:
      - MONGODB_URI=mongodb://admin:admin@mongodb:27017
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - HASHNODE_API_KEY=${HASHNODE_API_KEY}
      - TWITTER_API_KEY=${TWITTER_API_KEY}
      - TWITTER_API_SECRET=${TWITTER_API_SECRET}
      - TWITTER_ACCESS_TOKEN=${TWITTER_ACCESS_TOKEN}
      - TWITTER_ACCESS_TOKEN_SECRET=${TWITTER_ACCESS_TOKEN_SECRET}
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    networks:
      - flowforge-network
    volumes:
      - ./Backend:/app
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload

volumes:
  mongodb_data:
    driver: local

networks:
  flowforge-network:
    driver: bridge