version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: n8n_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: n8n_clone
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - n8n_network

  redis:
    image: redis:7.2-alpine
    container_name: n8n_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - n8n_network

  backend:
    build: ./Backend
    container_name: n8n_backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URL=mongodb://admin:password123@mongodb:27017/n8n_clone?authSource=admin
      - REDIS_URL=redis://redis:6379
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - HASHNODE_API_KEY=${HASHNODE_API_KEY}
      - TWITTER_API_KEY=${TWITTER_API_KEY}
      - TWITTER_API_SECRET=${TWITTER_API_SECRET}
      - TWITTER_ACCESS_TOKEN=${TWITTER_ACCESS_TOKEN}
      - TWITTER_ACCESS_TOKEN_SECRET=${TWITTER_ACCESS_TOKEN_SECRET}
    depends_on:
      - mongodb
      - redis
    volumes:
      - ./Backend:/app
    networks:
      - n8n_network

  frontend:
    build: ./Frontend
    container_name: flowforge_frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - backend
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    networks:
      - n8n_network

volumes:
  mongodb_data:
  redis_data:

networks:
  n8n_network:
    driver: bridge